### ISSUE TITLE
BMapGL.Polygon无法显示

### ISSUE THREAD

**Issue by xzf199803** [Leskur/bmap-crack#2]
大佬您好，想请问一下需要怎么修改，才能让BMapGL的区域覆盖物出现啊，

**Comment by Leskur** [comment]
@xzf199803 我写了个 demo 看起来 BMapGL.Polygon 是可以正常工作的。覆盖物没有出现，也许是别的原因导致。

**你需要将 ak 替换为你的密钥，地图才会显示。**

https://codesandbox.io/p/sandbox/admiring-bose-3d8p95

如果你不想在 codesandbox 运行，可以直接将 index.html 下载到本地运行。
